"""ondelete cascade added

Revision ID: 1fdc1d3985dc
Revises: 245462e46889
Create Date: 2025-10-01 22:34:19.266047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fdc1d3985dc'
down_revision: Union[str, Sequence[str], None] = '245462e46889'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('chapters_course_id_fkey'), 'chapters', type_='foreignkey')
    op.create_foreign_key(None, 'chapters', 'courses', ['course_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('sections_chapter_id_fkey'), 'sections', type_='foreignkey')
    op.create_foreign_key(None, 'sections', 'chapters', ['chapter_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sections', type_='foreignkey')
    op.create_foreign_key(op.f('sections_chapter_id_fkey'), 'sections', 'chapters', ['chapter_id'], ['id'])
    op.drop_constraint(None, 'chapters', type_='foreignkey')
    op.create_foreign_key(op.f('chapters_course_id_fkey'), 'chapters', 'courses', ['course_id'], ['id'])
    # ### end Alembic commands ###
