"""added difficulty field in roadmap

Revision ID: cf2fb933b5d8
Revises: e34e4870eff1
Create Date: 2025-11-26 15:39:07.720162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf2fb933b5d8'
down_revision: Union[str, Sequence[str], None] = 'e34e4870eff1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roadmaps', sa.Column('difficulty', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roadmaps', 'difficulty')
    # ### end Alembic commands ###
